config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources 'quants'
  resources 'general_sciences'
  resources 'reasonings'

  # Defines the root path route ("/")
  root 'contents#index'

  get '/redirect', to: 'contents#redirect', as: :url

  # DataImport paths
  resources :data_imports, only: %i[new create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/content.rb
# frozen_string_literal: true

class Content < ApplicationRecord
  paginates_per 10

  validates :question, presence: true
  validates :optional_answers, presence: true
  validates :answer, presence: true
end

app/models/data_import.rb
# frozen_string_literal: true

class DataImport < ApplicationRecord
  has_one_attached :xlsx_file

  def import_data
    xlsx = Roo::Spreadsheet.open(xlsx_file)
    xlsx.each_row do |row|
      # Process each row of data
    end
  end
end

app/models/general_science.rb
# frozen_string_literal: true

class GeneralScience < Content
end

app/models/quant.rb
# frozen_string_literal: true

class Quant < Content
end

app/models/reasoning.rb
# frozen_string_literal: true

class Reasoning < Content
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/concerns/subject_type_constant.rb
# frozen_string_literal: true

module SubjectTypeConstant
  SUB_TYPE = [
    { name: 'Select contents type', url: '' },
    { name: 'Maths', url: '/quants' },
    { name: 'Reasoning', url: '/reasonings' },
    { name: 'General Science', url: '/general_sciences' }
  ].freeze
end

app/controllers/contents_controller.rb
# frozen_string_literal: true

class ContentsController < ApplicationController
  include SubjectTypeConstant
  def index
    @urls = SUB_TYPE
  end

  # def redirect
  #   redirect_to params['url'].split('3000').last
  # end
end

app/controllers/data_imports_controller.rb
# frozen_string_literal: true

class DataImportsController < ApplicationController
  def new
    @data_import = DataImport.new
  end

  def create
    @data_import = DataImport.new(data_import_params)

    if @data_import.save
      flash[:success] = 'Data imported successfully!'
      redirect_to root_path
    else
      flash.now[:error] = 'Error importing data.'
      render :new
    end
  end

  private

  def data_import_params
    params.require(:data_import).permit(:xlsx_file)
  end
end

app/controllers/general_sciences_controller.rb
# frozen_string_literal: true

class GeneralSciencesController < ApplicationController
  before_action :current_general_science, only: %i[edit show update]
  include SubjectTypeConstant

  def index
    @general_sciences = GeneralScience.page(params[:page].to_i).per(10)
    @urls = SUB_TYPE

    respond_to do |format|
      format.html
      format.json { render json: @general_sciences }
    end
  end

  def new
    @general_science = GeneralScience.new
  end

  def create
    general_science = GeneralScience.new(general_science_params)
    if general_science.save
      flash[:success] = 'Added successfully!!!'
      redirect_to general_sciences_url
    else
      render :new
    end
  rescue StandardError => e
    flash[:error] = "An error occurred: #{e.message}"
    redirect_to root_url
  end

  def update
    if @general_science.update(quant_params)
      flash[:success] = 'Updated successfully!!!'
      redirect_to general_sciences_url
    else
      render :edit
    end
  rescue StandardError => e
    flash[:error] = "An error occurred: #{e.message}"
    redirect_to root_url
  end

  private

  def general_science_params
    params.require(:general_science).permit(:question, :optional_answers, :answer, :type)
  end

  def current_general_science
    @general_science = GeneralScience.find(params['id'])
  end
end

app/controllers/quants_controller.rb
# frozen_string_literal: true

class QuantsController < ApplicationController
  before_action :current_quant, only: %i[edit show update]
  include SubjectTypeConstant

  DEFAULT_PAGE = 1

  def index
    @quants = Quant.page(params[:page].to_i).per(8)
    @urls = SUB_TYPE

    respond_to do |format|
      format.html
      format.json { render json: @quants }
    end
  end

  def new
    @quant = Quant.new
  end

  def create
    quant = Quant.new(quant_params)
    if quant.save
      flash[:success] = 'New question added successfully!'
      redirect_to quants_url
    else
      render :new
    end
  rescue StandardError => e
    flash[:error] = "An error occurred: #{e.message}"
    redirect_to root_url
  end

  def update
    if @quant.update(quant_params)
      flash[:success] = 'Updated successfully!!!'
      redirect_to quants_url
    else
      render :edit
    end
  rescue StandardError => e
    flash[:error] = "An error occurred: #{e.message}"
    redirect_to root_url
  end

  private

  def quant_params
    params.require(:quant).permit(:question, :optional_answers, :answer, :type)
  end

  def current_quant
    @quant = Quant.find(params['id'])
  end
end

app/controllers/reasonings_controller.rb
# frozen_string_literal: true

class ReasoningsController < ApplicationController
  before_action :current_reasoning, only: %i[edit show update]
  include SubjectTypeConstant

  def index
    @reasonings = Reasoning.page(params[:page].to_i).per(10)
    @urls = SUB_TYPE

    respond_to do |format|
      format.html
      format.json { render json: @reasonings }
    end
  end

  def new
    @reasoning = Reasoning.new
  end

  def create
    reasoning = Reasoning.new(reasoning_params)
    if reasoning.save
      flash[:success] = 'New question added successfully'
      redirect_to reasonings_url
    else
      render :new
    end
  rescue StandardError => e
    flash[:error] = "An error occurred: #{e.message}"
    redirect_to root_url
  end

  def edit; end

  def update
    if @reasoning.update(reasoning_params)
      flash[:success] = 'Updated successfully!!!'
      redirect_to reasonings_url
    else
      render :edit
    end
  rescue StandardError => e
    flash[:error] = "An error occurred: #{e.message}"
    redirect_to root_url
  end

  private

  def current_reasoning
    @reasoning = Reasoning.find(params['id'])
  end

  def reasoning_params
    params.require(:reasoning).permit(:question, :optional_answers, :answer, :type)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/contents_helper.rb
# frozen_string_literal: true

module ContentsHelper
end

app/helpers/data_imports_helper.rb
# frozen_string_literal: true

module DataImportsHelper
end

app/helpers/general_sciences_helper.rb
# frozen_string_literal: true

module GeneralSciencesHelper
end

app/helpers/quants_helper.rb
# frozen_string_literal: true

module QuantsHelper
end

app/helpers/reasonings_helper.rb
# frozen_string_literal: true

module ReasoningsHelper
end

app/views/contents/create.html.erb
<h1>Contents#create</h1>
<p>Find me in app/views/contents/create.html.erb</p>

app/views/data_imports/create.html.erb
<div>
  <h1 class="font-bold text-4xl">DataImports#create</h1>
  <p>Find me in app/views/data_imports/create.html.erb</p>
</div>

app/views/data_imports/new.html.erb
<%= form_with(url: data_imports_path, local: true, multipart: true) do |form| %>
  <div>
    <%= form.label :xlsx_file %>
    <%= form.file_field :xlsx_file %>
  </div>

  <div>
    <%= form.submit "Upload File" %>
  </div>
<% end %>

app/views/general_sciences/create.html.erb
<div>
  <h1 class="font-bold text-4xl">GeneralSciences#create</h1>
  <p>Find me in app/views/general_sciences/create.html.erb</p>
</div>

app/views/general_sciences/edit.html.erb
<div class="w-full max-h-full px-10 bg-white border border-gray-200 rounded-lg shadow sm:p-10 md:p-8 dark:bg-gray-800 dark:border-gray-700">
  <div class=' p-8'>
    <p style='font-style: bold'> <strong>Add New question answer</strong> </p>

    <%= form_for @general_science, url: "/general_sciences/#{@general_science.id}", method: "put" do |f| %>
      <div class="space-y-18">
        <div class="pb-15">
          <div class="">
            <div class="mt-5">
              <%= f.label :question, "Question:", for: "question", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_area :question, size:20,  class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400"%>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :optional_answers, "Optional answer:",for: "optional_answers", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <p style="color: #ba8c63; font-style: italic; my-2">Note: Format for optional answer : {'0' => 'option 1', '1' => 'option 2', '2' => 'option 3', '3' => 'option 4'}</p>
              <div class="mt-2">
                <%= f.text_area :optional_answers, size:200, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :answer, "Currect Answer:",for: "answer", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_field :answer, size:200, class: " w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
            </div>
          </div>
        </div>

        <%= f.submit "Update", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center	' %>
      <% end %>

    <%= link_to "Question list", general_sciences_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center" %>
    <%= link_to "Home", root_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center" %>

  </div>
</div>

app/views/general_sciences/index.html.erb
<div class="w-full max-h-full px-10 bg-white border border-gray-200 rounded-lg shadow sm:p-10 md:p-8 dark:bg-gray-800 dark:border-gray-700 inline-flex">
  <div class="left_container">
    <% if flash[:success] %>
      <div class="flash_alelrt bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
        <span class="block sm:inline"><%= flash[:success] %></span>
        <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
          <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <title>Close</title>
            <path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/>
          </svg>
        </span>
      </div>
    <% end %>

    <h2> <strong>GeneralScience questions: </strong></h2>
    <hr>
    <ul>
      <% @general_sciences.each_with_index do |quant, index| %>
        <li class= 'mb-3'>
          <p> Question <%= index + 1 %>: <%= quant.question %> </p>
          <p> Optional answer: <%= quant.optional_answers %> </p>
          <p> Currect Answer: <%= quant.answer %> </p>
          <%= link_to "Edit", edit_general_science_url(quant), class: "text-sky-400 py-1.5", style:"color: blue" %>
        </li>
      <% end %>
    </ul>

    <%= paginate @general_sciences %>
  </div>
  <div class="right_container">
    <%= link_to "Add a new question", new_quant_url, class: "add_new_content" %>
  
    <%= form_tag(root_path, method: 'get', id: 'url-form', class:"rounded-lg text-sm px-5 py-2.5 text-center me-2 mt-2") do %>
      <%= select_tag 'url', options_for_select(@urls.map { |u| [u[:name], u[:url]] }), onchange: 'submitForm(this)' %>
    <% end %>
  </div>
</div>

<script>
  setTimeout(function() {
    document.getElementsByClassName("flash_alelrt")[0].remove();
  }, 3000);

  function submitForm(select) {
    var selectedUrl = select.options[select.selectedIndex].value;
    window.location.href = selectedUrl;
  }
</script>

app/views/quants/edit.html.erb
<div class="w-full max-h-full px-10 bg-white border border-gray-200 rounded-lg shadow sm:p-10 md:p-8 dark:bg-gray-800 dark:border-gray-700">
  <div class=' p-8'>
    <p style='font-style: bold'> <strong>Add New question answer</strong> </p>

    <%= form_for @quant, url: "/quants/#{@quant.id}", method: "put" do |f| %>
      <div class="space-y-18">
        <div class="pb-15">
          <div class="">
            <div class="mt-5">
              <%= f.label :question, "Question:", for: "question", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_area :question, size:20,  class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400"%>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :optional_answers, "Optional answer:",for: "optional_answers", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <p style="color: #ba8c63; font-style: italic; my-2">Note: Format for optional answer : {'0' => 'option 1', '1' => 'option 2', '2' => 'option 3', '3' => 'option 4'}</p>
              <div class="mt-2">
                <%= f.text_area :optional_answers, size:200, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :answer, "Currect Answer:",for: "answer", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_field :answer, size:200, class: " w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
            </div>
          </div>
        </div>

        <%= f.submit "Update", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center	' %>
      <% end %>

    <%= link_to "Question list", quants_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center" %>
    <%= link_to "Home", root_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center" %>

  </div>
</div>

app/views/quants/index.html.erb
<div class="w-full max-h-full px-10 bg-white border border-gray-200 rounded-lg shadow sm:p-10 md:p-8 dark:bg-gray-800 dark:border-gray-700 inline-flex">
  <div class="left_container">
    <% if flash[:success] %>
      <div class="flash_alelrt bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
        <span class="block sm:inline"><%= flash[:success] %></span>
        <span class="absolute top-0 bottom-0 right-0 px-4 py-3 close_button">
          <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
            <title>Close</title>
            <path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/>
          </svg>
        </span>
      </div>
    <% end %>
      
    <h2> <strong>Math questions: </strong></h2>
    <hr>
    <ul>
      <% @quants.each_with_index do |quant, index| %>
        <li class= 'mb-3'>
          <p> <strong>Q<%= index + 1 %></strong>: <%= quant.question %> </p>
          <p> Optional answer: <%= quant.optional_answers %> </p>
          <p> Currect Answer: <%= quant.answer %> </p>
          <%= link_to "Edit", edit_quant_url(quant), class: "text-sky-400 py-1.5", style:"color: blue" %>
        </li>
      <% end %>
    </ul>

    <%= paginate @quants, style: "color: red;" %>
  </div>
  <div class="right_container">
    <%= link_to "Add a new question", new_quant_url, class: "add_new_content" %>
  
    <%= form_tag(root_path, method: 'get', id: 'url-form', class:"rounded-lg text-sm px-5 py-2.5 text-center me-2 mt-2") do %>
      <%= select_tag 'url', options_for_select(@urls.map { |u| [u[:name], u[:url]] }), onchange: 'submitForm(this)' %>
    <% end %>

    <%= form_with(url: data_imports_path, local: true, multipart: true) do |form| %>
      <div>
        <%= form.label :xlsx_file, "Select Excel File (.xlsx) for Bulk Upload" %>
        <%= form.file_field :xlsx_file %>

        <%= form.submit "Submit",class: "add_new_content" %>
      </div>
    <% end %>    
  </div>
</div>

<script>
  setTimeout(function() {
    document.getElementsByClassName("flash_alelrt")[0]?.remove();
  }, 3000);


  function submitForm(select) {
    var selectedUrl = select.options[select.selectedIndex].value;
    window.location.href = selectedUrl;
  }
</script>

app/views/quants/new.html.erb
<div class="w-full max-h-full px-10 bg-white border border-gray-200 rounded-lg shadow sm:p-10 md:p-8 dark:bg-gray-800 dark:border-gray-700">
  <div class=' p-8'>
    <p style='font-style: bold'> <strong>Add New question answer</strong> </p>

    <%= form_for @quant, url: "/quants", method: "post" do |f| %>
      <div class="space-y-18">
        <div class="pb-15">
          <div class="">
            <div class="mt-5">
              <%= f.label :question, "Question:", for: "question", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_area :question, size:20,  class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400"%>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :optional_answers, "Optional answer:",for: "optional_answers", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <p style="color: #ba8c63; font-style: italic; my-2">Note: Format for optional answer : {'0' => 'option 1', '1' => 'option 2', '2' => 'option 3', '3' => 'option 4'}</p>
              <div class="mt-2">
                <%= f.text_area :optional_answers, size:200, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :answer, "Currect Answer:",for: "answer", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_field :answer, size:200, class: " w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
          </div>
        </div>
      </div>

      <%= f.submit "Add", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center	' %>
    <% end %>

    <%= link_to "Question list", quants_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-3 px-10 mt-4 rounded-full self-center" %>
    <%= link_to "Home", root_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center" %>

    </div>
</div>

app/views/reasonings/edit.html.erb
<div class="w-full max-h-full px-10 bg-white border border-gray-200 rounded-lg shadow sm:p-10 md:p-8 dark:bg-gray-800 dark:border-gray-700">
  <div class='p-8'>
    <p style='font-style: bold'> <strong>Add New question answer</strong> </p>

    <%= form_for @reasoning, url: "/reasonings/#{@reasoning.id}", method: "put" do |f| %>
      <div class="space-y-18">
        <div class="pb-15">
          <div class="">
            <div class="mt-5">
              <%= f.label :question, "Question:", for: "question", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_area :question, size:20,  class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400"%>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :optional_answers, "Optional answer:",for: "optional_answers", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <p style="color: #ba8c63; font-style: italic; my-2">Note: Format for optional answer : {'0' => 'option 1', '1' => 'option 2', '2' => 'option 3', '3' => 'option 4'}</p>
              <div class="mt-2">
                <%= f.text_area :optional_answers, size:200, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :answer, "Currect Answer:",for: "answer", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_field :answer, size:200, class: " w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
            </div>
          </div>
        </div>

        <%= f.submit "Update", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center	' %>
      <% end %>

    <%= link_to "Question list", reasonings_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center" %>
    <%= link_to "Home", root_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center" %>

  </div>
</div>

app/views/reasonings/index.html.erb
<div class="w-full max-h-full px-10 bg-white border border-gray-200 rounded-lg shadow sm:p-10 md:p-8 dark:bg-gray-800 dark:border-gray-700 inline-flex">
  <div class="left_container">
    <% if flash[:success] %>
      <div class="flash_alelrt bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
        <span class="block sm:inline"><%= flash[:success] %></span>
        <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
          <svg class="fill-current h-6 w-6 text-green-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
        </span>
      </div>
    <% end %>

    <h2> <strong>Reasoning questions: </strong></h2>
    <ul>
      <% @reasonings.each_with_index do |quant, index| %>
        <li class= 'mb-3'>
          <p> Question <%= index + 1 %>: <%= quant.question %> </p>
          <p> Optional answer: <%= quant.optional_answers %> </p>
          <p> Currect Answer: <%= quant.answer %> </p>
          <%= link_to "Edit", edit_reasoning_url(quant), class: "text-sky-400 py-1.5", style:"color: blue" %>
        </li>
      <% end %>
    </ul>

    <%= paginate @reasonings %>
  </div>
  <div class="right_container">
    <%= link_to "Add a new question", new_reasoning_url, class: "add_new_content" %>

    <%= form_tag(root_path, method: 'get', id: 'url-form', class:"rounded-lg text-sm px-5 py-2.5 text-center me-2 mt-2") do %>
      <%= select_tag 'url', options_for_select(@urls.map { |u| [u[:name], u[:url]] }), onchange: 'submitForm(this)' %>
    <% end %>
  </div>
</div>

<script>
  setTimeout(function() {
    document.getElementsByClassName("flash_alelrt")[0].remove();
  }, 3000);


  function submitForm(select) {
    var selectedUrl = select.options[select.selectedIndex].value;
    window.location.href = selectedUrl;
  }
</script>

app/views/reasonings/new.html.erb
<div class="w-full max-h-full px-10 bg-white border border-gray-200 rounded-lg shadow sm:p-10 md:p-8 dark:bg-gray-800 dark:border-gray-700">
  <div class=' p-8'>
    <p style='font-style: bold'> <strong>Add New question answer</strong> </p>

    <%= form_for @reasoning, url: "/reasonings", method: "post" do |f| %>
      <div class="space-y-18">
        <div class="pb-15">
          <div class="">
            <div class="mt-5">
              <%= f.label :question, "Question:", for: "question", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_area :question, size:20,  class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400"%>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :optional_answers, "Optional answer:",for: "optional_answers", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <p style="color: #ba8c63; font-style: italic; my-2">Note: Format for optional answer : {'0' => 'option 1', '1' => 'option 2', '2' => 'option 3', '3' => 'option 4'}</p>
              <div class="mt-2">
                <%= f.text_area :optional_answers, size:200, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
            </div>

            <div class="mt-5">
              <%= f.label :answer, "Currect Answer:",for: "answer", class: "block text-sm font-medium leading-6 text-gray-900" %>
              <div class="mt-2">
                <%= f.text_field :answer, size:200, class: " w-full rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400" %>
              </div>
            </div>
          </div>
        </div>

        <%= f.submit "Add", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center	' %>
      <% end %>

    <%= link_to "Question list", reasonings_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center" %>
    <%= link_to "Home", root_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-10 mt-4 rounded-full self-center" %>

  </div>
</div>